# Base configs
baseurl: "http://mutuak.netlify.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Mutua Kyale"
subtitle: ""
author: "Jabali Ndungu"
bio: "
web_design: "Jabali Ndungu"
social_urls:
  facebook: ""
  twitter: ""
  instagram: "https://www.instagram.com/p/BcmA6oAlFgh/?taken-by=mutua.kyale"
  dribbble: ""
  linkedin: ""
  github: ""
  
