---
baseurl: "http://mutuak.netlify.com/"
url: "http://mutuak.netlifiy.com"
image_fulls_loc: "/images/fulls"

image_thumbs_loc: "/images/thumbs"

---



# UI configs

title: "Photography by Mutua Kyale"

subtitle: ""

author: "Vincent Mutua Kyale"

bio: "Hello there, my name's are Vincent Mutua Kyale but most people call me Mutua. I am a 17 year old amature photographer, I have always had an interest in visual arts and I try my hardest to express my emotions through my lens. This is the beginning of the beginning of my journey. Strap up cause I'm about to take you on this ride... All the support is much appreciated."

web_design: "Jabali Ndungu   

social_urls:



  instagram: "https://www.instagram.com/mutua.kyale/"
